{smcl}
{* *! version 1.0 21Aug2018}{...}
{cmd:help xtplfc}{right: ({browse "https://doi.org/10.1177/1536867X20976339":SJ20-4: st0624})}
{hline}

{title:Title}

{p2colset 5 15 17 2}{...}
{p2col:{cmd:xtplfc} {hline 2}}Partially linear functional-coefficient panel-data models{p_end}
{p2colreset}{...}


{title:Syntax}

{p 8 14 2}
{cmd:xtplfc}
{varlist}{cmd:,}
{cmdab:z:vars(}{varlist}{cmd:)}
{cmdab:u:vars(}{varlist}{cmd:)}
{cmdab:gen:erate(}{it:prefix}{cmd:)} 
[{it:options}]

{pstd}
{opt xtplfc} can be used only if data are declared to be panel data through
the {helpb xtset} or {helpb tsset} command.  Before using {opt xtplfc}, you
must install {opt bspline} (Newson 2000) and {opt moremata} (Jann 2005).

{synoptset 28 tabbed}{...}
{synopthdr}
{synoptline}
{p2coldent :* {cmdab:z:vars(}{it:{help varlist:varlist}}{cmd:)}}specify variables that have functional coefficients{p_end}
{p2coldent :* {cmdab:u:vars(}{it:varlist}{cmd:)}}specify variables that enter into the functions{p_end}
{p2coldent :* {cmdab:gen:erate(}{it:prefix}{cmd:)}}specify a prefix for the names to store fitted values of functional coefficients{p_end}
{synopt :{opt te}}specify to include time fixed effects{p_end}
{synopt :{opt power(numlist)}}specify the power (or degree) of the splines for the functions{p_end}
{synopt:{opt nk:nots(numlist)}}specify the number of knots used for the spline interpolation{p_end}
{synopt:{opt quan:tile}}specify creating knots based on empirical quantiles{p_end}
{synopt:{opt maxnk:nots(numlist)}}specify the maximum number of knots used for
performing least-squares cross-validation (LSCV){p_end}
{synopt:{opt minnk:nots(numlist)}}specify the minimum number of knots used for performing LSCV{p_end}
{synopt :{opt grid(string)}}specify the name for storing the grid points of
the variable specified by {cmd:uvars(varlist)}{p_end}
{synopt :{opt pctile(#)}}specify the domain of the generating grid points; default is {cmd:pctile(0)}{p_end}
{synopt :{opt brep(#)}}specify the number of bootstrap replications; default is {cmd:brep(200)}{p_end}
{synopt :{opt wild}}specify using the wild bootstrap; by default, residual
bootstrap with {opt cluster(panelvar)} is performed{p_end}
{synopt :{opt predict(prspec)}}store predicted values of
the conditional mean and fixed effects using variable names specified in {it:prspec}{p_end}
{synopt :{opt nodots}}suppress iteration dots{p_end}
{synopt :{opt level(#)}}set confidence level; default is {cmd:level(95)}{p_end}
{synopt :{opt fast}}speed up using Mata functions{p_end}
{synopt :{opt ten:foldcv}}specify using tenfold cross-validation (CV) instead of LSCV{p_end}
{synoptline}
{p2colreset}{...}
{p 4 6 2}* {cmd:zvars()}, {cmd:uvars()}, and {cmd:generate()} are required.{p_end}
{p 4 6 2}Note: Unbalanced panel data must be rectangularized in advance; use
{helpb tsfill:tsfill, full}.{p_end}


{title:Description}

{pstd}
{opt xtplfc} fits An, Hsiao, and Li's (2016) partially linear
functional-coefficient panel-data models.

{pstd}
The model can be expressed as

{phang2}
Y_it=X_it'*beta+Z_it'*G(U_it)+a_i+e_it

{pstd}
where subscripts i and t present individual and time period, respectively;
X_it and Z_it are vectors of covariates, respectively; G(U_it) is a vector of
functional coefficients and U_it is a vector of continuous variables
[specifically, Z_it'*G(U_it)=sum{Z_jit*G_j(U_jit)}]; a_i represents the fixed
effects; and e_it is the idiosyncratic error.

{pstd}
We approximate the functional coefficients by a linear combination of B-spline
base functions.  The fixed effects are removed by the first time difference.
Then, the transformed model is estimated through the least-squares technique.


{title:Options}

{phang}
{cmd:zvars(}{it:{help varlist:varlist}}{cmd:)} specifies the variables that
have functional coefficients.  {cmd:zvars()} is required.

{phang}
{cmd:uvars(}{it:varlist}{cmd:)} specifies (continuous) variables that enter
into the functional coefficients interacted with variables in order specified
by {cmd:zvars()}.  {cmd:uvars()} is required.

{phang}
{cmd:generate(}{it:prefix}{cmd:)} specifies a prefix for the variable names to
store fitted values of functional coefficients.  {cmd:generate()} is required.

{phang}
{opt te} specifies to include time fixed effects.

{phang}
{opt power(numlist)} (nonnegative integers) specifies the power (or degree) of
the splines in order specified by {cmd:uvars()}.  The default is
{cmd:power(3)}.

{phang}
{opt nknots(numlist)} specifies the number of knots used for the spline
interpolation in order specified by {cmd:uvars()}.  The default is
{cmd:nknots(2)}.

{phang}
{opt quantile} specifies creating knots based on empirical quantiles.  By
default, the knots are generated by the rule of equal space.

{phang}
{opt maxnknots(numlist)} specifies the maximum number of knots used for
conducting LSCV.  If present, LSCV is used to determine the optimal number of
knots.  In our practice, we perform the leave-one-out CV across the
{it:panelvar}.  That is to say, we leave one individual (with all observations
during the sample period) out each time.

{phang}
{opt minnknots(numlist)} specifies the minimum number of knots used for
performing LSCV.  The default is {cmd:minnknots(2)}.

{phang}
{opt grid(string)} specifies a prefix for the names to store the grid points
of the variable specified by {opt uvars(varname)}.  If present, the functional
coefficients are estimated over the grid points.  By default, they are
estimated over the observations.

{phang}
{opt pctile(#)} specifies the domain of the generating grid points.  It
can be only used when {opt grid()} is specified.  The default is
{cmd:pctile(0)}.

{phang}
{opt brep(#)} specifies the number of bootstrap replications.  The default is
{cmd:brep(200)}.  We recommend that you select the number of replications.

{phang}
{opt wild} specifies using the wild bootstrap.  By default, residual bootstrap
with the option {opt cluster(panelvar)} is performed.

{phang}
{opt predict(prspec)} stores predicted values of the conditional mean and
fixed effects using variable names specified in {it:prspec}.  {it:prspec} is
the following:

{phang2}
{cmd:predict(}{varlist}|{it:stub}{cmd:*} [{cmd:, replace noai}]{cmd:)}

{pmore}
The option takes a variable list or {it:stub}.  The first variable name
corresponds to the predicted conditional mean.  The second name corresponds to
fixed effects.

{pmore}
When {cmd:replace} is used, variables with the names in {it:varlist} or
{it:stub}{cmd:*} are replaced by those in the new computation.  If {cmd:noai}
is specified, only a variable for the mean is created.

{phang}
{opt nodots} suppresses the iteration dots.

{phang}
{opt level(#)} sets the confidence level.  The default is {cmd:level(95)}.

{phang}
{opt fast} speeds up using Mata functions.

{phang}
{opt tenfoldcv} specifies using tenfold CV instead of LSCV.  It is done by
dividing the sample into 10 pieces and conducting LSCV across
these 10 pieces.  Specifically, given the number of knots, leave one
piece out, run the regression using the left pieces, and predict the
dependent variable for the remaining piece.


{title:Examples}

{pstd}Setup{p_end}
{phang2}{cmd:.} {bf:{stata "set obs 50"}}{p_end}
{phang2}{cmd:.} {bf:{stata "generate a=rnormal()"}}{p_end}
{phang2}{cmd:.} {bf:{stata "generate id=_n"}}{p_end}
{phang2}{cmd:.} {bf:{stata "expand 100"}}{p_end}
{phang2}{cmd:.} {bf:{stata "bysort id: generate year=_n"}}{p_end}
{phang2}{cmd:.} {bf:{stata "generate x=10*runiform()"}}{p_end}
{phang2}{cmd:.} {bf:{stata "generate z=5+2*rnormal()"}}{p_end}
{phang2}{cmd:.} {bf:{stata "generate u=-3+20*runiform()"}}{p_end}
{phang2}{cmd:.} {bf:{stata "generate gf1=sin(_pi/3*u)"}}{p_end}
{phang2}{cmd:.} {bf:{stata "generate y=a+1.2*x+z*gf1+sqrt(2)*rnormal()"}}{p_end}
{phang2}{cmd:.} {bf:{stata "xtset id year"}}{p_end}

{pstd}
Fixed-effects semiparametric regression with 10 knots specified{p_end}
{phang2}
{cmd:.} {bf:{stata "xtplfc y x, zvars(z) uvars(u) generate(g) nknots(10)"}}{p_end}

{pstd}
Fixed-effects semiparametric regression with optimal knots determined by the
rule of leave-one-out CV{p_end}
{phang2}
{cmd:.} {bf:{stata "xtplfc y x, zvars(z) uvars(u) generate(f) maxnknots(20)"}}{p_end}

{pstd}
Compute the 95% confidence interval for the functional coefficient{p_end}
{phang2}{cmd:.} {bf:{stata "generate lb=f_1-1.96*f_1_sd"}}{p_end}
{phang2}{cmd:.} {bf:{stata "generate ub=f_1+1.96*f_1_sd"}}{p_end}

{pstd}
Plot the fitted values of the functional coefficient{p_end}
{phang2}{cmd:.} {bf:{stata "local plot1 line gf1 u, sort"}}{p_end}
{phang2}{cmd:.} {bf:{stata "local plot2 line f_1 u, sort"}}{p_end}
{phang2}{cmd:.} {bf:{stata "local plot3 rarea lb ub u, color(gs12) sort"}}{p_end}
{phang2}{cmd:.} {bf:{stata `"twoway (`plot3') (`plot1') (`plot2' legend(label(1 "95% CI") label(2 "Real values") label(3 "Fitted values")))"'}}{p_end}
 

{title:Stored results}

{pstd}
{cmd:xtplfc} stores the following in {cmd:e()}:

{synoptset 15 tabbed}{...}
{p2col 5 15 19 2: Scalars}{p_end}
{synopt:{cmd:e(N)}}number of individuals{p_end}
{synopt:{cmd:e(df_m)}}model degrees of freedom{p_end}
{synopt:{cmd:e(df_r)}}residual degrees of freedom{p_end}
{synopt:{cmd:e(r2)}}within R-squared{p_end}
{synopt:{cmd:e(r2_a)}}adjusted within R-squared{p_end}
{synopt:{cmd:e(rmse)}}root mean squared error{p_end}
{synopt:{cmd:e(mss)}}model sum of squares{p_end}
{synopt:{cmd:e(rss)}}residual sum of squares{p_end}

{synoptset 15 tabbed}{...}
{p2col 5 15 19 2: Macros}{p_end}
{synopt:{cmd:e(cmd)}}{cmd:xtplfc}{p_end}
{synopt:{cmd:e(depvar)}}name of dependent variable{p_end}
{synopt:{cmd:e(title)}}title in estimation output{p_end}
{synopt:{cmd:e(estfun)}}variables storing the estimated functional coefficients{p_end}
{synopt:{cmd:e(properties)}}{cmd:b V}{p_end}
{synopt:{cmd:e(vcetype)}}type of variance-covariance{p_end}
{synopt:{cmd:e(model)}}{cmd:Fixed-effect Series Semiparametric Estimation}{p_end}
{synopt:{cmd:e(k}{it:#}{cmd:)}}list of knots for the {it:#}th function{p_end}

{synoptset 15 tabbed}{...}
{p2col 5 15 19 2: Matrices}{p_end}
{synopt:{cmd:e(b)}}coefficient vector in the linear part{p_end}
{synopt:{cmd:e(V)}}variance-covariance matrix of the estimators in the linear part{p_end}
{synopt:{cmd:e(bs)}}coefficient vector in the approximating model{p_end}
{synopt:{cmd:e(Vs)}}variance-covariance matrix of the estimators in the approximating model{p_end}
{synopt:{cmd:e(nknots)}}number of knots{p_end}
{synopt:{cmd:e(power)}}power (or degree) of splines{p_end}
{p2colreset}{...}


{marker references}{...}
{title:References}

{phang}
An, Y., C. Hsiao, and D. Li. 2016. Semiparametric estimation of
partially linear varying coefficient panel data models. In
{it:Essays in Honor of Aman Ullah} ({it:Advances in Econometrics, Volume 36}),
ed. G. Gonz{c a'}lez-Rivera, R. C. Hill, and T.-H. Lee, 47-65.
Bingley, UK: Emerald.
{browse "https://doi.org/10.1108/S0731-905320160000036011"}.

{phang}
Jann, B. 2005. moremata: Stata module (Mata) to provide various functions.
Statistical Software Components S455001, Department of Economics, Boston
College.  {browse "https://ideas.repec.org/c/boc/bocode/s455001.html"}.

{phang}
Newson, R. B. 2000. bspline: Stata modules to compute B-splines parameterized
by their values at reference points. Statistical Software Components S411701,
Department of Economics, Boston College. 
{browse "https://ideas.repec.org/c/boc/bocode/s411701.html"}.



{title:Authors}

{pstd}
Kerry Du{break}
School of Management{break}
Xiamen University{break}
Xiamen, China{break}
{browse "mailto:kerrydu@xmu.edu.cn":kerrydu@xmu.edu.cn}

{pstd}
Yonghui Zhang{break}
School of Economics{break}
Renmin University of China{break}
Beijing, China{break}
{browse "mailto:yonghui.zhang@hotmail.com":yonghui.zhang@hotmail.com}

{pstd}
Qiankun Zhou{break}
Department of Economics{break}
Renmin University of China{break}
Baton Rouge, LA{break}
{browse "mailto:qzhou@lsu.edu":qzhou@lsu.edu}


{title:Also see}

{p 4 14 2}
Article:  {it:Stata Journal}, volume 20, number 4: {browse "https://doi.org/10.1177/1536867X20976339":st0624}{p_end}

{p 7 14 2}
Help:  {helpb xtdplfc}, {helpb ivxtplfc}, {helpb xtsemipar}, {helpb bspline} (if installed){p_end}
