#!/bin/bash
# CNKI batch downloader backed by the project literature registry.
# Usage: kns8s-download.sh <cookie-file> <paper-workspace> <download-plan.tsv>
# The plan is generated by ../literature_registry.py download-plan. Its three
# columns are paper_id, project-relative pdf_path, and PDF URL.
set -u

COOKIE_FILE="${1:?用法: kns8s-download.sh <cookie文件> <paper-workspace> <download-plan.tsv>}"
WORKSPACE="${2:?缺少 paper-workspace 路径}"
PLAN="${3:?缺少由 literature_registry.py 生成的下载计划}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REGISTRY_TOOL="${SCRIPT_DIR}/../literature_registry.py"
LIT_ROOT="${WORKSPACE%/}/02-literature"
UA="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36"
MAX_BATCH=15
DELAY_SECONDS=6

[ -s "$COOKIE_FILE" ] || { echo "错误: cookie 文件为空: $COOKIE_FILE" >&2; exit 1; }
[ -s "$PLAN" ] || { echo "错误: 下载计划为空: $PLAN" >&2; exit 1; }
[ -f "$REGISTRY_TOOL" ] || { echo "错误: 未找到文献注册表工具: $REGISTRY_TOOL" >&2; exit 1; }
COOKIE="$(cat "$COOKIE_FILE")"

processed=0
ok=0
failed=0
blocked=0

while IFS=$'\t' read -r paper_id pdf_rel url; do
  case "$paper_id" in ""|"paper_id"|\#*) continue ;; esac
  [ -n "$pdf_rel" ] && [ -n "$url" ] || continue
  case "$pdf_rel" in
    papers/*) ;;
    *) echo "$paper_id: INVALID 计划中的 PDF 路径不在 papers/: $pdf_rel" >&2; failed=$((failed + 1)); continue ;;
  esac
  case "/$pdf_rel/" in
    *"/../"*|*"/./"*) echo "$paper_id: INVALID 计划中的 PDF 路径包含相对目录: $pdf_rel" >&2; failed=$((failed + 1)); continue ;;
  esac

  if [ "$processed" -ge "$MAX_BATCH" ]; then
    echo "已达到单批 ${MAX_BATCH} 篇上限；剩余条目保留为待下载，请在风控冷却后生成新计划续跑。" >&2
    break
  fi
  processed=$((processed + 1))
  out="${LIT_ROOT}/${pdf_rel}"
  mkdir -p "$(dirname "$out")"

  if [ -s "$out" ] && python3 "$REGISTRY_TOOL" validate-pdf --path "$out" >/dev/null; then
    python3 "$REGISTRY_TOOL" mark-download --workspace "$WORKSPACE" --paper-id "$paper_id" --pdf-path "$out" >/dev/null
    echo "$paper_id: SKIP 已验证归档"
    ok=$((ok + 1))
    continue
  fi

  part="${out}.part"
  rm -f "$part"
  code_type="$(curl -sSL --max-time 90 \
    -H "Cookie: $COOKIE" -H "Referer: https://kns.cnki.net/" -H "User-Agent: $UA" \
    -o "$part" -w "%{http_code} %{content_type}" "$url")"
  curl_status=$?
  code="${code_type%% *}"
  ctype="${code_type#* }"

  if [ "$curl_status" -ne 0 ]; then
    rm -f "$part"
    python3 "$REGISTRY_TOOL" mark-download-failure --workspace "$WORKSPACE" --paper-id "$paper_id" --status retry --note "curl 错误" >/dev/null
    echo "$paper_id: FAIL curl 错误"
    failed=$((failed + 1))
    continue
  fi

  if ! python3 "$REGISTRY_TOOL" validate-pdf --path "$part" >/dev/null; then
    rm -f "$part"
    note="HTTP ${code}; content-type=${ctype:-unknown}；疑似 Cookie、令牌或频控页"
    python3 "$REGISTRY_TOOL" mark-download-failure --workspace "$WORKSPACE" --paper-id "$paper_id" --status blocked --note "$note" >/dev/null
    echo "$paper_id: BLOCKED $note；停止本批，等待用户完成可见验证码或风控冷却。" >&2
    blocked=1
    break
  fi

  mv -f "$part" "$out"
  if python3 "$REGISTRY_TOOL" mark-download --workspace "$WORKSPACE" --paper-id "$paper_id" --pdf-path "$out" >/dev/null; then
    echo "$paper_id: OK $code $(stat -f%z "$out" 2>/dev/null || echo 0)B"
    ok=$((ok + 1))
  else
    echo "$paper_id: FAIL 注册表写回失败" >&2
    failed=$((failed + 1))
  fi
  [ "$processed" -lt "$MAX_BATCH" ] && sleep "$DELAY_SECONDS"
done < "$PLAN"

echo "有效归档: $ok / 失败: $failed / 阻断: $blocked / 本批处理: $processed"
[ "$failed" -eq 0 ] && [ "$blocked" -eq 0 ]
